from __future__ import annotations

DEFAULT_GEMINI_CONFIDENCE_THRESHOLD = 0.7
DEFAULT_GEMINI_FREE_DAILY_REQUEST_LIMIT = 1500
DEFAULT_GEMINI_FREE_DAILY_IMAGE_LIMIT = 1000
DEFAULT_GEMINI_TEMPERATURE = 0.2
DEFAULT_GEMINI_TOP_K = 40
DEFAULT_GEMINI_TOP_P = 0.95
DEFAULT_GEMINI_MAX_OUTPUT_TOKENS = 2048
DEFAULT_GEMINI_OCR_MAX_OUTPUT_TOKENS = 4096
DEFAULT_GEMINI_MAX_OUTPUT_TOKENS_HARD_CAP = 32768
MAX_GEMINI_MAX_OUTPUT_TOKENS_HARD_CAP = 65536
DEFAULT_GEMINI_CONSISTENCY_MIN_RATIO = 0.7
