from __future__ import annotations

AUTOMATIC_OCR_REQUIRES_HUMAN_REVIEW = "AUTOMATIC_OCR_REQUIRES_HUMAN_REVIEW"
NEEDS_REVIEW_FLAG = "NEEDS_REVIEW_FLAG"
MIN_TEXT_LENGTH = "MIN_TEXT_LENGTH"
HAS_UNCLEAR = "HAS_UNCLEAR"
