[mypy]
python_version = 3.12
plugins = mypy_django_plugin.main

# Start in "medium" - tighten later
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = False
warn_unreachable = True

check_untyped_defs = False
disallow_untyped_defs = False

no_implicit_optional = True
strict_optional = True

# Keep noise low initially
ignore_missing_imports = True

# Your Django project settings
[mypy.plugins.django-stubs]
django_settings_module = vs_archive.settings
