# Generated by Django 6.0.1 on 2026-01-26 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("language", models.CharField(max_length=16)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("IMAGE", "Image")], max_length=16
                    ),
                ),
                ("category_event", models.CharField(max_length=255)),
                ("tags", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        default="private",
                        max_length=16,
                    ),
                ),
                (
                    "upload_status",
                    models.CharField(
                        choices=[
                            ("UPLOADING", "Uploading"),
                            ("UPLOADED", "Uploaded"),
                            ("FAILED", "Failed"),
                        ],
                        default="UPLOADING",
                        max_length=16,
                    ),
                ),
                (
                    "file_s3_key",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "file_original_name",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("mime_type", models.CharField(blank=True, default="", max_length=128)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("upload_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CorrectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("DATA", "Data"), ("METADATA", "Metadata")],
                        max_length=16,
                    ),
                ),
                ("field_path", models.CharField(blank=True, max_length=512, null=True)),
                ("message", models.TextField()),
                (
                    "requester_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "requester_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="documents.document",
                    ),
                ),
            ],
        ),
    ]
