# Generated by Django 6.0.1 on 2026-01-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="metadata_status",
            field=models.CharField(
                choices=[
                    ("NEEDS_COMPLETION", "Needs completion"),
                    ("COMPLETED", "Completed"),
                ],
                default="NEEDS_COMPLETION",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="category_event",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="date_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="date_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="language",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
