# Generated by Django 6.0.1 on 2026-02-01 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_metadata_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="processing_state_user",
            field=models.CharField(
                choices=[
                    ("PROCESSING", "Processing"),
                    ("READY", "Ready"),
                    ("PARTIAL", "Partial"),
                    ("ACTION_REQUIRED", "Action required"),
                    ("FAILED", "Failed"),
                ],
                default="PROCESSING",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="DocumentTextResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("SOURCE_TEXT", "Source text"),
                            ("HEBREW_TEXT", "Hebrew text"),
                        ],
                        max_length=32,
                    ),
                ),
                ("engine", models.CharField(default="engine_v1", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("NEEDS_REVIEW", "Needs review"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("UNVERIFIED", "Unverified"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="UNVERIFIED",
                        max_length=32,
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("error_details", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_results",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["document", "result_type", "engine"],
                        name="documents_d_documen_3a886c_idx",
                    ),
                    models.Index(
                        fields=["status", "verification_status"],
                        name="documents_d_status_b8a439_idx",
                    ),
                ],
            },
        ),
    ]
