# Generated by Django 6.0.1 on 2026-02-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_processing_state_user_documenttextresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="tags_m2m",
            field=models.ManyToManyField(
                blank=True, related_name="documents", to="documents.tag"
            ),
        ),
    ]
