# Generated by Django 6.0.1 on 2026-02-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_tag_document_tags_m2m"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="document",
            name="tags",
        ),
        migrations.AddField(
            model_name="tag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["name"], name="documents_t_name_00dfa6_idx"),
        ),
    ]
