# Generated by Django 6.0.1 on 2026-02-03 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_alter_tag_options_remove_document_tags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("donor", models.CharField(blank=True, default="", max_length=255)),
                (
                    "collection",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "original_location",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_meta",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["donor"], name="documents_d_donor_ddbed8_idx"),
                    models.Index(
                        fields=["collection"], name="documents_d_collect_84ace2_idx"
                    ),
                ],
            },
        ),
    ]
