# Generated by Django 6.0.1 on 2026-02-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_documentmetadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="metadata",
        ),
        migrations.AddIndex(
            model_name="documentmetadata",
            index=models.Index(
                fields=["original_location"], name="documents_d_origina_c6a996_idx"
            ),
        ),
    ]
