# Generated by Django 6.0.1 on 2026-02-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_document_language_choices"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="documenttextresult",
            constraint=models.UniqueConstraint(
                fields=("document", "result_type", "engine"),
                name="uniq_document_resulttype_engine",
            ),
        ),
    ]
