# Generated by Django 6.0.1 on 2026-02-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_documenttextresult_uniq_document_resulttype_engine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="processing_state_user",
            field=models.CharField(
                choices=[
                    ("PROCESSING", "Processing"),
                    ("READY", "Ready"),
                    ("PARTIAL", "Partial"),
                    ("FAILED", "Failed"),
                ],
                default="PROCESSING",
                max_length=32,
            ),
        ),
    ]
