# Generated by Django 6.0.1 on 2026-02-16 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_alter_document_processing_state_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("UPLOAD", "Upload"),
                            ("PAGE_EXTRACTION", "Page extraction"),
                            ("OCR_HTR", "OCR/HTR"),
                            ("TRANSLATION", "Translation"),
                            ("POSTPROCESS", "Postprocess"),
                            ("PIPELINE", "Pipeline total"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Metric name within stage, e.g. duration, pages, chars, api_calls, etc.",
                        max_length=64,
                    ),
                ),
                ("engine", models.CharField(blank=True, default="", max_length=64)),
                ("attempt_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ms", "Milliseconds"),
                            ("s", "Seconds"),
                            ("bytes", "Bytes"),
                            ("pages", "Pages"),
                            ("chars", "Characters"),
                            ("tokens", "Tokens"),
                            ("count", "Count"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("value_int", models.BigIntegerField(blank=True, null=True)),
                ("value_float", models.FloatField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="STARTED",
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("error_details", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_metrics",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["document", "stage", "name"],
                        name="documents_p_documen_b6bd60_idx",
                    ),
                    models.Index(
                        fields=["stage", "name", "created_at"],
                        name="documents_p_stage_e3357d_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="documents_p_status_a6b4e0_idx",
                    ),
                    models.Index(
                        fields=["engine", "created_at"],
                        name="documents_p_engine_99b3de_idx",
                    ),
                ],
            },
        ),
    ]
