# Generated by Django 6.0.1 on 2026-02-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_processingmetric"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttextresult",
            name="review_reasons",
            field=models.TextField(blank=True, default=""),
        ),
    ]
