# Generated by Django 6.0.4 on 2026-05-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_documenttextresult_ocr_observability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttextresult',
            name='engine_key',
            field=models.CharField(choices=[('GEMINI', 'Gemini'), ('TRANSKRIBUS', 'Transkribus')], max_length=32),
        ),
    ]
