# Generated by Django 6.0.1 on 2026-05-24 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_documenttextresult_ocrenginekey_transkribus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranskribusRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('UPLOADED', 'Uploaded'), ('RECOGNITION_STARTED', 'Recognition started'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='STARTED', max_length=32)),
                ('mode', models.CharField(choices=[('UPLOAD_CREATED', 'Upload created'), ('EXISTING_SERVER', 'Existing server document')], max_length=32)),
                ('collection_id', models.CharField(max_length=64)),
                ('model_id', models.CharField(max_length=64)),
                ('remote_doc_id', models.CharField(blank=True, help_text='TrpServer docId when known.', max_length=64, null=True)),
                ('pages_query', models.CharField(blank=True, help_text='Trp pages= query used for recognition/metadata.', max_length=512, null=True)),
                ('page_index_to_page_nr', models.JSONField(blank=True, default=None, help_text='VS-Archive page_index → Trp pageNr (upload mode).', null=True)),
                ('upload_id', models.BigIntegerField(blank=True, null=True)),
                ('ingest_job_id', models.CharField(blank=True, max_length=128, null=True)),
                ('recognition_job_id', models.CharField(blank=True, max_length=128, null=True)),
                ('engine_runtime', models.CharField(blank=True, help_text='Runtime engine string, e.g. transkribus-pylaia:{model_id}.', max_length=255, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transkribus_runs', to='documents.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document', '-created_at'], name='tr_run_doc_created_idx'), models.Index(fields=['document', 'status'], name='tr_run_doc_status_idx'), models.Index(fields=['remote_doc_id'], name='tr_run_remote_doc_idx'), models.Index(fields=['status', 'created_at'], name='tr_run_status_created_idx')],
            },
        ),
    ]
