# Generated by Django 6.0.1 on 2026-05-28 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0016_transkribusrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_index",
                    models.IntegerField(
                        help_text="Zero-based position among this document's source files."
                    ),
                ),
                ("file_s3_key", models.CharField(max_length=1024)),
                (
                    "file_original_name",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("mime_type", models.CharField(blank=True, default="", max_length=128)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_files",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "order_index"),
                        name="uniq_document_sourcefile_order",
                    ),
                    models.UniqueConstraint(
                        fields=("document", "file_s3_key"),
                        name="uniq_document_sourcefile_s3_key",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("order_index__gte", 0)),
                        name="dsf_order_index_gte_0",
                    ),
                ],
            },
        ),
    ]
