# Generated by Django 6.0.1 on 2026-05-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0017_documentsourcefile"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="expected_source_file_count",
            field=models.IntegerField(
                blank=True,
                help_text="Planned multi-image source file count when set at create; null for legacy single-file documents.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentsourcefile",
            name="upload_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentsourcefile",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("UPLOADED", "Uploaded"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
