# Generated by Django 6.0.1 on 2026-06-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0018_multi_image_upload_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="date_precision",
            field=models.CharField(
                choices=[
                    ("EXACT_DAY", "Exact day"),
                    ("MONTH", "Month"),
                    ("YEAR", "Year"),
                    ("RANGE", "Range"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=16,
            ),
        ),
    ]
