# Generated by Django 6.0.1 on 2026-06-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0022_archiveitem_source_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ArchiveEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("date_start", models.DateField(blank=True, null=True)),
                ("date_end", models.DateField(blank=True, null=True)),
                (
                    "date_precision",
                    models.CharField(
                        choices=[
                            ("EXACT_DAY", "Exact day"),
                            ("MONTH", "Month"),
                            ("YEAR", "Year"),
                            ("RANGE", "Range"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="archiveitem",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="archive_items", to="documents.tag"
            ),
        ),
        migrations.AddField(
            model_name="archiveitem",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="archive_items", to="documents.archivecategory"
            ),
        ),
        migrations.AddField(
            model_name="archiveitem",
            name="events",
            field=models.ManyToManyField(
                blank=True, related_name="archive_items", to="documents.archiveevent"
            ),
        ),
    ]
