# Generated by Django 6.0.1 on 2026-06-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_archive_discovery_metadata_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivecategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='archiveevent',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
