# Generated by Django 6.0.1 on 2026-06-09 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0024_archive_category_event_name_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_file_key", models.CharField(max_length=1024)),
                ("original_filename", models.CharField(max_length=512)),
                ("original_mime_type", models.CharField(max_length=128)),
                ("original_size_bytes", models.PositiveBigIntegerField()),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "thumbnail_file_key",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "thumbnail_mime_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "thumbnail_size_bytes",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archive_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_content",
                        to="documents.archiveitem",
                    ),
                ),
            ],
        ),
    ]
