# Generated by Django 6.0.1 on 2026-06-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0025_photocontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="photocontent",
            name="upload_error",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="photocontent",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("UPLOADED", "Uploaded"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="photocontent",
            name="original_size_bytes",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
