# Generated by Django 6.0.1 on 2026-06-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0026_photocontent_upload_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="photocontent",
            name="context",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="photocontent",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="photocontent",
            name="location",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="photocontent",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="photocontent",
            name="people_present",
            field=models.TextField(blank=True, default=""),
        ),
    ]
