# Generated by Django 6.0.1 on 2026-06-15 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0028_transcription_edit_suggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptioneditsuggestion",
            name="approved_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcriptioneditsuggestion",
            name="applied_text_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_transcription_edit_suggestions",
                to="documents.documenttextresult",
            ),
        ),
    ]
