# Generated by Django 6.0.1 on 2026-06-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0029_transcription_edit_suggestion_review_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttextresult",
            name="prompt_variant",
            field=models.CharField(
                choices=[
                    ("handwritten", "Handwritten"),
                    ("printed", "Printed"),
                    ("hebrew_translation", "Hebrew translation"),
                ],
                max_length=32,
            ),
        ),
    ]
