# Generated by Django 6.0.1 on 2026-06-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_hebrew_based_on_source_revision(apps, schema_editor):
    DocumentTextResult = apps.get_model("documents", "DocumentTextResult")
    for hebrew in DocumentTextResult.objects.filter(result_type="HEBREW_TEXT"):
        source = DocumentTextResult.objects.filter(
            document_id=hebrew.document_id,
            result_type="SOURCE_TEXT",
            engine=hebrew.engine,
        ).first()
        if source is not None:
            hebrew.based_on_source_revision = source.source_revision
            hebrew.save(update_fields=["based_on_source_revision"])


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0030_documenttextresult_hebrew_translation_prompt_variant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttextresult",
            name="based_on_source_revision",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documenttextresult",
            name="source_revision",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="DocumentTextResultEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                ("old_text", models.TextField()),
                ("new_text", models.TextField()),
                (
                    "edit_type",
                    models.CharField(
                        choices=[
                            ("SOURCE_TEXT", "Source text"),
                            ("HEBREW_TEXT", "Hebrew text"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_text_result_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "text_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edits",
                        to="documents.documenttextresult",
                    ),
                ),
            ],
            options={
                "ordering": ["-edited_at"],
            },
        ),
        migrations.RunPython(
            backfill_hebrew_based_on_source_revision,
            migrations.RunPython.noop,
        ),
    ]
