# Generated by Django 6.0.1 on 2026-07-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0034_archiveitem_public_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="date_end",
        ),
        migrations.RemoveField(
            model_name="document",
            name="date_precision",
        ),
        migrations.RemoveField(
            model_name="document",
            name="date_start",
        ),
        migrations.RemoveField(
            model_name="document",
            name="metadata_status",
        ),
        migrations.RemoveField(
            model_name="document",
            name="title",
        ),
        migrations.RemoveField(
            model_name="document",
            name="visibility",
        ),
    ]
