# Generated by Django 6.0.1 on 2026-07-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0035_remove_document_date_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="first_page_height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="first_page_width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="thumbnail_file_key",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="document",
            name="thumbnail_mime_type",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="document",
            name="thumbnail_size_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
