# Generated by Django 6.0.1 on 2026-07-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0036_document_thumbnail_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archiveevent",
            name="date_precision",
            field=models.CharField(
                choices=[
                    ("EXACT_DAY", "Exact day"),
                    ("MONTH", "Month"),
                    ("YEAR", "Year"),
                    ("RANGE", "Exact day range"),
                    ("RANGE_MONTH", "Month range"),
                    ("RANGE_YEAR", "Year range"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="archiveitem",
            name="date_precision",
            field=models.CharField(
                choices=[
                    ("EXACT_DAY", "Exact day"),
                    ("MONTH", "Month"),
                    ("YEAR", "Year"),
                    ("RANGE", "Exact day range"),
                    ("RANGE_MONTH", "Month range"),
                    ("RANGE_YEAR", "Year range"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=16,
            ),
        ),
    ]
