# Generated by Django 6.0.1 on 2026-07-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0037_alter_archiveevent_date_precision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="handwriting_type",
            field=models.CharField(
                choices=[
                    ("VS", "VS handwriting"),
                    ("GENERAL", "General Hebrew handwriting"),
                ],
                default="VS",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="documenttextresult",
            name="prompt_variant",
            field=models.CharField(
                choices=[
                    ("handwritten", "Handwritten"),
                    ("hebrew_general_handwritten", "General Hebrew handwriting"),
                    ("printed", "Printed"),
                    ("hebrew_translation", "Hebrew translation"),
                ],
                max_length=32,
            ),
        ),
    ]
