# Generated by Django 6.0.1 on 2026-07-20 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0038_document_handwriting_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TranskribusTranscriptSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("AUTOMATIC_HTR", "Automatic HTR"),
                            ("CORRECTED_CURRENT_SYNC", "Corrected-current sync"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "remote_doc_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "collection_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("model_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "recognition_job_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("parser_version", models.CharField(max_length=64)),
                (
                    "provider_identity_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 of ordered page_index:tsId lines. Not unique.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "raw_xml_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 of ordered per-page PAGE XML SHA-256 digests.",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("canonical_text", models.TextField(blank=True, default="")),
                (
                    "canonical_text_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "geometry_capability",
                    models.CharField(
                        choices=[
                            ("VERIFIED", "Verified"),
                            ("PARTIAL", "Partial"),
                            ("NOT_AVAILABLE", "Not available"),
                            ("INDETERMINATE", "Indeterminate"),
                        ],
                        default="INDETERMINATE",
                        max_length=32,
                    ),
                ),
                ("hover_eligible", models.BooleanField(default=False)),
                (
                    "storage_status",
                    models.CharField(
                        choices=[
                            ("PENDING_UPLOAD", "Pending upload"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING_UPLOAD",
                        max_length=32,
                    ),
                ),
                (
                    "remote_status_summary",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transkribus_transcript_snapshots_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transkribus_transcript_snapshots",
                        to="documents.document",
                    ),
                ),
                (
                    "transkribus_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcript_snapshots",
                        to="documents.transkribusrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranskribusTextResultBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "binding_role",
                    models.CharField(
                        choices=[
                            ("SNAPSHOT_SOURCE", "Snapshot source text"),
                            ("HEBREW_MIRROR", "Hebrew mirror of snapshot text"),
                        ],
                        default="SNAPSHOT_SOURCE",
                        max_length=32,
                    ),
                ),
                ("bound_text_sha256", models.CharField(max_length=64)),
                ("bound_source_revision", models.PositiveIntegerField()),
                ("bound_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bound_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transkribus_text_result_bindings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "text_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transkribus_snapshot_binding",
                        to="documents.documenttextresult",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_result_bindings",
                        to="documents.transkribustranscriptsnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranskribusSnapshotPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_index",
                    models.PositiveIntegerField(
                        help_text="1-based local page index (matches PageImage.page_index)."
                    ),
                ),
                (
                    "page_nr",
                    models.PositiveIntegerField(help_text="Transkribus pageNr."),
                ),
                ("transcript_ts_id", models.CharField(max_length=64)),
                ("provider_page_id", models.BigIntegerField(blank=True, null=True)),
                ("image_width", models.PositiveIntegerField(blank=True, null=True)),
                ("image_height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "image_filename",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "page_namespace",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "remote_transcript_status",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Observed provider transcript status; not verification.",
                        max_length=64,
                    ),
                ),
                (
                    "page_xml_s3_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Future S3 key for raw PAGE XML; unused in schema PR.",
                        max_length=1024,
                    ),
                ),
                (
                    "page_xml_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("text_region_count", models.PositiveIntegerField(default=0)),
                ("text_line_count", models.PositiveIntegerField(default=0)),
                ("lines_with_non_empty_text", models.PositiveIntegerField(default=0)),
                ("duplicate_line_ids", models.PositiveIntegerField(default=0)),
                ("reading_order_present", models.BooleanField(default=False)),
                ("reading_order_resolved", models.BooleanField(default=False)),
                (
                    "lines_xml_order_differs_from_reading_order",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "page_geometry_capability",
                    models.CharField(
                        choices=[
                            ("VERIFIED", "Verified"),
                            ("PARTIAL", "Partial"),
                            ("NOT_AVAILABLE", "Not available"),
                            ("INDETERMINATE", "Indeterminate"),
                        ],
                        default="INDETERMINATE",
                        max_length=32,
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="documents.transkribustranscriptsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["page_index"],
            },
        ),
        migrations.CreateModel(
            name="TranskribusSnapshotLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        help_text="Zero-based order among retained lines in XML document order."
                    ),
                ),
                (
                    "provider_region_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "provider_line_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("contributes_to_canonical", models.BooleanField(default=True)),
                ("char_start", models.PositiveIntegerField()),
                ("char_end", models.PositiveIntegerField()),
                (
                    "polygon_points",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "baseline_points",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("bbox_min_x", models.FloatField(blank=True, null=True)),
                ("bbox_min_y", models.FloatField(blank=True, null=True)),
                ("bbox_max_x", models.FloatField(blank=True, null=True)),
                ("bbox_max_y", models.FloatField(blank=True, null=True)),
                ("coords_valid", models.BooleanField(default=False)),
                ("baseline_valid", models.BooleanField(default=False)),
                ("has_meaningful_geometry", models.BooleanField(default=False)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="documents.transkribussnapshotpage",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("page", "order_index"), name="uniq_tr_snap_line_order"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("char_end__gte", models.F("char_start"))),
                        name="tr_snap_line_char_end_gte_start",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="transkribustranscriptsnapshot",
            index=models.Index(
                fields=["document", "-created_at"], name="tr_snap_doc_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transkribustranscriptsnapshot",
            index=models.Index(
                fields=["document", "storage_status"], name="tr_snap_doc_storage_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transkribustranscriptsnapshot",
            index=models.Index(
                fields=["raw_xml_fingerprint"], name="tr_snap_raw_xml_fp_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribustranscriptsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("storage_status", "READY"),
                    ("raw_xml_fingerprint__isnull", False),
                    models.Q(("raw_xml_fingerprint", ""), _negated=True),
                ),
                fields=("document", "parser_version", "raw_xml_fingerprint"),
                name="uniq_tr_snap_ready_raw_xml",
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribustranscriptsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("storage_status", "READY"), _negated=True),
                    models.Q(
                        ("provider_identity_fingerprint__isnull", False),
                        models.Q(("provider_identity_fingerprint", ""), _negated=True),
                        ("raw_xml_fingerprint__isnull", False),
                        models.Q(("raw_xml_fingerprint", ""), _negated=True),
                        models.Q(("canonical_text_sha256", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="tr_snap_ready_requires_fingerprints",
            ),
        ),
        migrations.AddIndex(
            model_name="transkribustextresultbinding",
            index=models.Index(fields=["snapshot"], name="tr_bind_snapshot_idx"),
        ),
        migrations.AddConstraint(
            model_name="transkribussnapshotpage",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "page_index"), name="uniq_tr_snap_page_index"
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribussnapshotpage",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "page_nr"), name="uniq_tr_snap_page_nr"
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribussnapshotpage",
            constraint=models.CheckConstraint(
                condition=models.Q(("page_index__gte", 1)),
                name="tr_snap_page_index_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribussnapshotpage",
            constraint=models.CheckConstraint(
                condition=models.Q(("page_nr__gte", 1)), name="tr_snap_page_nr_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribussnapshotpage",
            constraint=models.CheckConstraint(
                condition=models.Q(("transcript_ts_id", ""), _negated=True),
                name="tr_snap_page_ts_id_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribussnapshotpage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("image_width__isnull", True),
                    ("image_width__gte", 1),
                    _connector="OR",
                ),
                name="tr_snap_page_image_width_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribussnapshotpage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("image_height__isnull", True),
                    ("image_height__gte", 1),
                    _connector="OR",
                ),
                name="tr_snap_page_image_height_positive",
            ),
        ),
    ]
