# Generated by Django 6.0.1 on 2026-07-22 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0040_transkribus_run_automatic_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TranskribusCorrectedCurrentSyncAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("COMPLETED", "Completed"),
                            ("REFUSED", "Refused"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "storage_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CREATED", "Created"),
                            ("REUSED_EXISTING", "Reused existing"),
                            ("REUSED_CONCURRENT_WINNER", "Reused concurrent winner"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "failure_message",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transkribus_corrected_current_sync_attempts",
                        to="documents.document",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transkribus_corrected_current_sync_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="corrected_current_sync_attempts",
                        to="documents.transkribustranscriptsnapshot",
                    ),
                ),
                (
                    "transkribus_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="corrected_current_sync_attempts",
                        to="documents.transkribusrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TranskribusCorrectedCurrentSyncPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_index",
                    models.PositiveIntegerField(
                        help_text="1-based local page index (matches PageImage.page_index)."
                    ),
                ),
                (
                    "page_nr",
                    models.PositiveIntegerField(help_text="Transkribus pageNr."),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("SELECTED", "Selected"), ("REFUSED", "Refused")],
                        max_length=16,
                    ),
                ),
                (
                    "transcript_ts_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "remote_transcript_status",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Observed provider transcript status; not verification.",
                        max_length=64,
                    ),
                ),
                ("in_progress_warning", models.BooleanField(default=False)),
                (
                    "selection_error_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ZERO_TRANSCRIPTS", "Zero transcripts"),
                            ("MULTIPLE_TRANSCRIPTS", "Multiple transcripts"),
                            ("MISSING_TS_ID", "Missing tsId"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "selection_error_message",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="documents.transkribuscorrectedcurrentsyncattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["page_index"],
            },
        ),
        migrations.AddIndex(
            model_name="transkribuscorrectedcurrentsyncattempt",
            index=models.Index(
                fields=["document", "-created_at"], name="tr_cc_sync_doc_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transkribuscorrectedcurrentsyncattempt",
            index=models.Index(
                fields=["document", "status"], name="tr_cc_sync_doc_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribuscorrectedcurrentsyncattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["STARTED", "COMPLETED", "REFUSED", "FAILED"])
                ),
                name="tr_cc_sync_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribuscorrectedcurrentsyncattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("storage_outcome__isnull", True),
                    (
                        "storage_outcome__in",
                        ["CREATED", "REUSED_EXISTING", "REUSED_CONCURRENT_WINNER"],
                    ),
                    _connector="OR",
                ),
                name="tr_cc_sync_storage_outcome_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribuscorrectedcurrentsyncattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "STARTED"), _negated=True),
                    models.Q(
                        ("completed_at__isnull", True),
                        ("resolved_snapshot__isnull", True),
                        ("storage_outcome__isnull", True),
                        ("failure_code__isnull", True),
                        ("failure_message__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="tr_cc_sync_started_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribuscorrectedcurrentsyncattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "COMPLETED"), _negated=True),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("resolved_snapshot__isnull", False),
                        ("storage_outcome__isnull", False),
                        ("failure_code__isnull", True),
                        ("failure_message__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="tr_cc_sync_completed_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribuscorrectedcurrentsyncattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "REFUSED"), _negated=True),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("resolved_snapshot__isnull", True),
                        ("storage_outcome__isnull", True),
                        ("failure_code__isnull", True),
                        ("failure_message__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="tr_cc_sync_refused_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribuscorrectedcurrentsyncattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "FAILED"), _negated=True),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("failure_code__isnull", False),
                        models.Q(("failure_code", ""), _negated=True),
                        ("resolved_snapshot__isnull", True),
                        ("storage_outcome__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="tr_cc_sync_failed_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribuscorrectedcurrentsyncpage",
            constraint=models.CheckConstraint(
                condition=models.Q(("outcome__in", ["SELECTED", "REFUSED"])),
                name="tr_cc_sync_page_outcome_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribuscorrectedcurrentsyncpage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("selection_error_code", ""),
                    (
                        "selection_error_code__in",
                        ["ZERO_TRANSCRIPTS", "MULTIPLE_TRANSCRIPTS", "MISSING_TS_ID"],
                    ),
                    _connector="OR",
                ),
                name="tr_cc_sync_selection_error_code_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribuscorrectedcurrentsyncpage",
            constraint=models.UniqueConstraint(
                fields=("attempt", "page_index"), name="uniq_tr_cc_sync_page_index"
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribuscorrectedcurrentsyncpage",
            constraint=models.UniqueConstraint(
                fields=("attempt", "page_nr"), name="uniq_tr_cc_sync_page_nr"
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribuscorrectedcurrentsyncpage",
            constraint=models.CheckConstraint(
                condition=models.Q(("page_index__gte", 1)),
                name="tr_cc_sync_page_index_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribuscorrectedcurrentsyncpage",
            constraint=models.CheckConstraint(
                condition=models.Q(("page_nr__gte", 1)), name="tr_cc_sync_page_nr_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribuscorrectedcurrentsyncpage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("outcome", "SELECTED"), _negated=True),
                    models.Q(
                        models.Q(("transcript_ts_id", ""), _negated=True),
                        ("selection_error_code", ""),
                        ("selection_error_message", ""),
                    ),
                    _connector="OR",
                ),
                name="tr_cc_sync_page_selected_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="transkribuscorrectedcurrentsyncpage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("outcome", "REFUSED"), _negated=True),
                    models.Q(
                        ("transcript_ts_id", ""),
                        models.Q(("selection_error_code", ""), _negated=True),
                        models.Q(("selection_error_message", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="tr_cc_sync_page_refused_shape",
            ),
        ),
    ]
