# Generated by Django 6.0.1 on 2026-07-23 13:11

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0041_transkribus_corrected_current_sync_attempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveItemSearchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_text", models.TextField(blank=True, default="")),
                ("metadata_text", models.TextField(blank=True, default="")),
                ("body_text", models.TextField(blank=True, default="")),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archive_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_index",
                        to="documents.archiveitem",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="archive_item_search_vector_gin"
                    )
                ],
            },
        ),
    ]
