# Generated by Django 6.0.1 on 2026-07-28 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0044_transkribus_corrected_current_sync_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessDocumentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("RECOVERY_REQUIRED", "Recovery required"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("ENQUEUE_FAILED", "Enqueue failed"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("OCR", "OCR"),
                            ("HEBREW_TRANSLATION", "Hebrew translation"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("UPLOAD_FINALIZE", "Upload finalize"),
                            ("OCR_REPROCESS", "OCR reprocess"),
                            ("HEBREW_TRANSLATION_RETRY", "Hebrew translation retry"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "ocr_retry_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal_reenqueue", "Normal re-enqueue"),
                            (
                                "transkribus_recognition_only",
                                "Transkribus recognition only",
                            ),
                        ],
                        default="",
                        max_length=48,
                    ),
                ),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "failure_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "failure_message",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_enqueued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_document_requests",
                        to="documents.document",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_process_document_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_transkribus_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="process_document_requests",
                        to="documents.transkribusrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "-created_at"],
                        name="proc_req_doc_created_idx",
                    ),
                    models.Index(
                        fields=["document", "status"], name="proc_req_doc_status_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "QUEUED",
                                    "RUNNING",
                                    "RECOVERY_REQUIRED",
                                    "COMPLETED",
                                    "FAILED",
                                    "ENQUEUE_FAILED",
                                ],
                            )
                        ),
                        name="proc_req_status_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "QUEUED",
                                    "RUNNING",
                                    "RECOVERY_REQUIRED",
                                    "ENQUEUE_FAILED",
                                ],
                            )
                        ),
                        fields=("document",),
                        name="uniq_process_req_active_doc",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("status__in", ["QUEUED", "ENQUEUE_FAILED"]),
                                _negated=True,
                            ),
                            models.Q(
                                ("lease_token__isnull", True),
                                ("lease_expires_at__isnull", True),
                                ("started_at__isnull", True),
                                ("completed_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="proc_req_queued_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "RUNNING"), _negated=True),
                            models.Q(
                                ("lease_token__isnull", False),
                                ("lease_expires_at__isnull", False),
                                ("started_at__isnull", False),
                                ("completed_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="proc_req_running_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "RECOVERY_REQUIRED"), _negated=True),
                            models.Q(
                                ("lease_token__isnull", False),
                                ("lease_expires_at__isnull", True),
                                ("started_at__isnull", False),
                                ("completed_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="proc_req_recovery_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("status__in", ["COMPLETED", "FAILED"]), _negated=True
                            ),
                            models.Q(
                                ("lease_token__isnull", True),
                                ("lease_expires_at__isnull", True),
                                ("completed_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="proc_req_terminal_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "COMPLETED"), _negated=True),
                            models.Q(("failure_code", ""), ("failure_message", "")),
                            _connector="OR",
                        ),
                        name="proc_req_completed_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("status__in", ["FAILED", "ENQUEUE_FAILED"]),
                                _negated=True,
                            ),
                            models.Q(("failure_code", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="proc_req_failure_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "ocr_retry_mode__in",
                                    [
                                        "normal_reenqueue",
                                        "transkribus_recognition_only",
                                    ],
                                ),
                                ("operation", "OCR"),
                            ),
                            models.Q(
                                ("ocr_retry_mode", ""),
                                ("operation", "HEBREW_TRANSLATION"),
                                ("source_transkribus_run__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="proc_req_operation_payload",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("ocr_retry_mode", "transkribus_recognition_only"),
                                ("source_transkribus_run__isnull", False),
                            ),
                            models.Q(
                                models.Q(
                                    ("ocr_retry_mode", "transkribus_recognition_only"),
                                    _negated=True,
                                ),
                                ("source_transkribus_run__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="proc_req_source_run_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("ocr_retry_mode", "normal_reenqueue"),
                                ("operation", "OCR"),
                                ("origin", "UPLOAD_FINALIZE"),
                            ),
                            models.Q(("operation", "OCR"), ("origin", "OCR_REPROCESS")),
                            models.Q(
                                ("operation", "HEBREW_TRANSLATION"),
                                ("origin", "HEBREW_TRANSLATION_RETRY"),
                            ),
                            _connector="OR",
                        ),
                        name="proc_req_origin_operation",
                    ),
                ],
            },
        ),
    ]
