# Generated by Django 6.0.1 on 2026-07-28 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0045_process_document_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="processdocumentrequest",
            name="proc_req_status_valid",
        ),
        migrations.RemoveConstraint(
            model_name="processdocumentrequest",
            name="proc_req_terminal_shape",
        ),
        migrations.AlterField(
            model_name="processdocumentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("RUNNING", "Running"),
                    ("RECOVERY_REQUIRED", "Recovery required"),
                    ("COMPLETED", "Completed"),
                    ("PARTIAL", "Partial"),
                    ("FAILED", "Failed"),
                    ("ENQUEUE_FAILED", "Enqueue failed"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="processdocumentrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "QUEUED",
                            "RUNNING",
                            "RECOVERY_REQUIRED",
                            "COMPLETED",
                            "PARTIAL",
                            "FAILED",
                            "ENQUEUE_FAILED",
                        ],
                    )
                ),
                name="proc_req_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="processdocumentrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["COMPLETED", "PARTIAL", "FAILED"]),
                        _negated=True,
                    ),
                    models.Q(
                        ("lease_token__isnull", True),
                        ("lease_expires_at__isnull", True),
                        ("completed_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="proc_req_terminal_shape",
            ),
        ),
    ]
