# Generated by Django 6.0.1 on 2026-08-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0047_gemini_ocr_page_checkpoints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="text_input_type",
            field=models.CharField(
                choices=[
                    ("HANDWRITTEN", "Handwritten"),
                    ("PRINTED", "Printed"),
                    ("MIXED", "Mixed printed and handwritten"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="documenttextresult",
            name="prompt_variant",
            field=models.CharField(
                choices=[
                    ("handwritten", "Handwritten"),
                    ("hebrew_general_handwritten", "General Hebrew handwriting"),
                    ("printed", "Printed"),
                    ("mixed", "Mixed printed and handwritten"),
                    ("hebrew_translation", "Hebrew translation"),
                ],
                max_length=32,
            ),
        ),
    ]
