# Generated by Django 6.0.1 on 2026-08-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0048_document_mixed_text_input_type_and_prompt_variant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archiveitem",
            options={
                "permissions": [
                    ("view_restricted_archiveitem", "Can view restricted archive items")
                ]
            },
        ),
        migrations.AlterField(
            model_name="archiveitem",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("public", "Public"),
                    ("restricted", "Restricted"),
                ],
                default="private",
                max_length=16,
            ),
        ),
    ]
