# Generated by Django 6.0.1 on 2026-08-05 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0049_archiveitem_restricted_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archiveitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("OCR_DOCUMENT", "OCR document"),
                    ("MANUAL_TEXT", "Manual text"),
                    ("PHOTO", "Photo"),
                    ("VIDEO", "Video"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="VideoContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.CharField(max_length=2048)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("YOUTUBE", "YouTube"),
                            ("KAN", "Kan"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "presentation_mode",
                    models.CharField(
                        choices=[
                            ("EMBEDDED", "Embedded"),
                            ("EXTERNAL_LINK", "External link"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "provider_video_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("start_seconds", models.IntegerField(blank=True, null=True)),
                ("end_seconds", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archive_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_content",
                        to="documents.archiveitem",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("provider__in", ["YOUTUBE", "KAN", "OTHER"])
                        ),
                        name="video_content_provider_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("presentation_mode__in", ["EMBEDDED", "EXTERNAL_LINK"])
                        ),
                        name="video_content_presentation_mode_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("presentation_mode", "EMBEDDED"),
                                ("provider", "YOUTUBE"),
                                (
                                    "provider_video_id__regex",
                                    "^[A-Za-z0-9_-]{11}$",
                                ),
                            ),
                            models.Q(
                                ("presentation_mode", "EXTERNAL_LINK"),
                                ("provider", "KAN"),
                                ("provider_video_id", ""),
                            ),
                            models.Q(
                                ("presentation_mode", "EXTERNAL_LINK"),
                                ("provider", "OTHER"),
                                ("provider_video_id", ""),
                            ),
                            _connector="OR",
                        ),
                        name="video_content_provider_mode_id_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("start_seconds__isnull", True),
                            ("start_seconds__gte", 0),
                            _connector="OR",
                        ),
                        name="video_content_start_seconds_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_seconds__isnull", True),
                            ("end_seconds__gt", 0),
                            _connector="OR",
                        ),
                        name="video_content_end_seconds_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_seconds__isnull", True),
                            models.Q(
                                ("start_seconds__isnull", True), ("end_seconds__gt", 0)
                            ),
                            ("end_seconds__gt", models.F("start_seconds")),
                            _connector="OR",
                        ),
                        name="video_content_end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("provider", "YOUTUBE"),
                            models.Q(
                                ("end_seconds__isnull", True),
                                ("start_seconds__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="video_content_times_youtube_only",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_url", ""), _negated=True),
                        name="video_content_source_url_nonempty",
                    ),
                ],
            },
        ),
    ]
