# Generated by Django 6.0.1 on 2026-08-13 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0050_video_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranskribusParagraphMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copied_from', models.ForeignKey(blank=True, help_text='Optional provenance when a manager later adopts a historical mapping.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_to_mappings', to='documents.transkribusparagraphmapping')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transkribus_paragraph_mappings_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transkribus_paragraph_mappings', to='documents.document')),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph_mapping', to='documents.transkribustranscriptsnapshot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transkribus_paragraph_mappings_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranskribusParagraphBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph_breaks_after', to='documents.transkribussnapshotline')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='documents.transkribusparagraphmapping')),
            ],
        ),
        migrations.AddIndex(
            model_name='transkribusparagraphmapping',
            index=models.Index(fields=['document', '-updated_at'], name='tr_para_map_doc_upd_idx'),
        ),
        migrations.AddConstraint(
            model_name='transkribusparagraphbreak',
            constraint=models.UniqueConstraint(fields=('mapping', 'after_line'), name='uniq_tr_para_break_after_line'),
        ),
    ]
