# Generated by Django 6.0.1 on 2026-08-17 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0051_transkribus_paragraph_mapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ArchiveItemPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "archive_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_links",
                        to="documents.archiveitem",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_item_links",
                        to="documents.person",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="archiveitem",
            name="people",
            field=models.ManyToManyField(
                blank=True,
                related_name="archive_items",
                through="documents.ArchiveItemPerson",
                to="documents.person",
            ),
        ),
        migrations.CreateModel(
            name="PhotoPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_links",
                        to="documents.person",
                    ),
                ),
                (
                    "photo_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_links",
                        to="documents.photocontent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="photocontent",
            name="people",
            field=models.ManyToManyField(
                blank=True,
                related_name="photo_contents",
                through="documents.PhotoPerson",
                to="documents.person",
            ),
        ),
        migrations.AddConstraint(
            model_name="archiveitemperson",
            constraint=models.UniqueConstraint(
                fields=("archive_item", "person"), name="uniq_archive_item_person"
            ),
        ),
        migrations.AddConstraint(
            model_name="photoperson",
            constraint=models.UniqueConstraint(
                fields=("photo_content", "person"), name="uniq_photo_person"
            ),
        ),
    ]
