# Generated by Django 6.0.1 on 2026-08-17 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0052_person_identity_foundation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photocontent",
            options={"ordering": ["archive_item", "position", "id"]},
        ),
        migrations.AddField(
            model_name="photocontent",
            name="date_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photocontent",
            name="date_precision",
            field=models.CharField(
                choices=[
                    ("EXACT_DAY", "Exact day"),
                    ("MONTH", "Month"),
                    ("YEAR", "Year"),
                    ("RANGE", "Exact day range"),
                    ("RANGE_MONTH", "Month range"),
                    ("RANGE_YEAR", "Year range"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="photocontent",
            name="date_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photocontent",
            name="position",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="photocontent",
            name="archive_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo_contents",
                to="documents.archiveitem",
            ),
        ),
        migrations.AddConstraint(
            model_name="photocontent",
            constraint=models.UniqueConstraint(
                fields=("archive_item", "position"),
                name="uniq_photocontent_archive_item_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="photocontent",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)),
                name="photocontent_position_gte_1",
            ),
        ),
    ]
