# Generated by Django 6.0.1 on 2026-08-28 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0057_person_biography"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ArchiveItemAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "archive_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_links",
                        to="documents.archiveitem",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_item_links",
                        to="documents.author",
                    ),
                ),
            ],
            options={
                "ordering": ["archive_item", "position", "id"],
            },
        ),
        migrations.AddField(
            model_name="archiveitem",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="archive_items",
                through="documents.ArchiveItemAuthor",
                to="documents.author",
            ),
        ),
        migrations.AddConstraint(
            model_name="archiveitemauthor",
            constraint=models.UniqueConstraint(
                fields=("archive_item", "author"), name="uniq_archive_item_author"
            ),
        ),
        migrations.AddConstraint(
            model_name="archiveitemauthor",
            constraint=models.UniqueConstraint(
                fields=("archive_item", "position"),
                name="uniq_archive_item_author_position",
            ),
        ),
    ]
