# Generated by Django 6.0.1 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0063_author_person_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="arabicprintedocrpagecheckpoint",
            name="operator_resolution_audit",
            field=models.JSONField(
                default=dict,
                help_text=(
                    "Durable operator fence-resolution audit "
                    "(arabic-printed-operator-fence-resolution-v1). "
                    "Worker claim/reclaim/success/failure must not clear this field."
                ),
            ),
        ),
    ]
