# Generated by Django 6.0.1 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0064_arabic_printed_page_operator_resolution_audit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="processing_state_user",
            field=models.CharField(
                choices=[
                    ("PROCESSING", "Processing"),
                    ("RECOVERY_REQUIRED", "Recovery required"),
                    ("READY", "Ready"),
                    ("PARTIAL", "Partial"),
                    ("FAILED", "Failed"),
                ],
                default="PROCESSING",
                max_length=32,
            ),
        ),
    ]
