# Generated by Django 6.0.1 on 2026-09-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0067_person_honorific"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transkribustranscriptsnapshot",
            name="source_kind",
            field=models.CharField(
                choices=[
                    ("AUTOMATIC_HTR", "Automatic HTR"),
                    ("CORRECTED_CURRENT_SYNC", "Corrected-current sync"),
                    ("LEGACY_IMPORT", "Legacy Transkribus import"),
                ],
                max_length=32,
            ),
        ),
    ]
