# Generated by Django 6.0.1 on 2026-09-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0070_person_registry_binding_and_family_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalias",
            name="kind",
            field=models.CharField(
                choices=[
                    ("unspecified", "לא צוין"),
                    ("other_language", "שם בשפה אחרת"),
                    ("cover_identity", "שם כיסוי"),
                    ("code_name", "שם קוד"),
                    ("underground_name", "שם מחתרתי"),
                    ("nickname", "כינוי / שם מוכר"),
                    ("name_variant", "וריאנט של השם"),
                    ("spelling_variant", "וריאנט איות"),
                    ("ocr_variant", "וריאנט OCR"),
                    ("partial_name", "שם חלקי"),
                    ("transliteration", "תעתיק"),
                    ("honorific_or_title", "צורה עם תואר"),
                    ("birth_name", "שם לידה"),
                    ("other", "אחר"),
                ],
                default="unspecified",
                max_length=32,
            ),
        ),
    ]
