# Generated by Django 6.0.1 on 2026-10-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0071_personalias_kind_expansion"),
    ]

    operations = [
        migrations.CreateModel(
            name="NonPersonEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canonical_name", models.CharField(max_length=255)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("PLACE", "PLACE"),
                            ("ORGANIZATION", "ORGANIZATION"),
                            ("COMMUNITY", "COMMUNITY"),
                            ("PUBLICATION_WORK", "PUBLICATION_WORK"),
                            ("LEGAL_INSTRUMENT", "LEGAL_INSTRUMENT"),
                            ("EVENT", "EVENT"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "entity_subtype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ASSOCIATION_OR_NGO", "ASSOCIATION_OR_NGO"),
                            ("BOOK", "BOOK"),
                            ("BUILDING", "BUILDING"),
                            ("CAMP", "CAMP"),
                            ("CITY", "CITY"),
                            ("COUNTRY", "COUNTRY"),
                            ("COURT_OR_JUDICIAL_BODY", "COURT_OR_JUDICIAL_BODY"),
                            ("COVERT_OPERATION", "COVERT_OPERATION"),
                            ("EDUCATIONAL_INSTITUTION", "EDUCATIONAL_INSTITUTION"),
                            ("ETHNO_RELIGIOUS_GROUP", "ETHNO_RELIGIOUS_GROUP"),
                            ("GOVERNMENT_BODY", "GOVERNMENT_BODY"),
                            ("HOSPITAL", "HOSPITAL"),
                            (
                                "IMMIGRATION_OR_RESCUE_BODY",
                                "IMMIGRATION_OR_RESCUE_BODY",
                            ),
                            ("INTELLIGENCE_ORGANIZATION", "INTELLIGENCE_ORGANIZATION"),
                            ("JEWISH_COMMUNITY", "JEWISH_COMMUNITY"),
                            ("LAW_OR_STATUTE", "LAW_OR_STATUTE"),
                            ("MILITARY_OR_SECURITY_SITE", "MILITARY_OR_SECURITY_SITE"),
                            ("NEIGHBORHOOD", "NEIGHBORHOOD"),
                            ("NEWSPAPER", "NEWSPAPER"),
                            ("ORDER_OR_DECREE", "ORDER_OR_DECREE"),
                            ("OTHER", "OTHER"),
                            ("PERIODICAL_OR_JOURNAL", "PERIODICAL_OR_JOURNAL"),
                            ("PRISON", "PRISON"),
                            ("REGION_OR_HISTORICAL_AREA", "REGION_OR_HISTORICAL_AREA"),
                            ("RELIGIOUS_SITE", "RELIGIOUS_SITE"),
                            (
                                "REPORT_OR_PROTOCOL_NON_LEGAL",
                                "REPORT_OR_PROTOCOL_NON_LEGAL",
                            ),
                            ("SCHOOL", "SCHOOL"),
                            ("VERDICT_OR_SENTENCE", "VERDICT_OR_SENTENCE"),
                            ("WAR_OR_CAMPAIGN", "WAR_OR_CAMPAIGN"),
                            ("YOUTH_MOVEMENT", "YOUTH_MOVEMENT"),
                            (
                                "ZIONIST_FEDERATION_OR_BODY",
                                "ZIONIST_FEDERATION_OR_BODY",
                            ),
                        ],
                        default="",
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["canonical_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="NonPersonEntityAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("LANGUAGE_VARIANT", "LANGUAGE_VARIANT"),
                            ("OCR_VARIANT", "OCR_VARIANT"),
                            ("SPELLING_VARIANT", "SPELLING_VARIANT"),
                            ("TRANSLITERATION_VARIANT", "TRANSLITERATION_VARIANT"),
                            ("ABBREVIATION", "ABBREVIATION"),
                            ("CURRENT_NAME", "CURRENT_NAME"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="documents.nonpersonentity",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity", "name"),
                        name="uniq_non_person_entity_alias_entity_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReviewedNonPersonEntityDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                ("candidate_id", models.CharField(max_length=255)),
                ("workbook_sha256", models.CharField(max_length=64)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROVE", "APPROVE"),
                            ("MERGE", "MERGE"),
                            ("SPLIT", "SPLIT"),
                            ("SKIP", "SKIP"),
                            ("NEEDS_RESEARCH", "NEEDS_RESEARCH"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[("CLOSED", "CLOSED"), ("UNRESOLVED", "UNRESOLVED")],
                        max_length=16,
                    ),
                ),
                (
                    "final_canonical",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "merge_target_candidate_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("contextual_surfaces", models.TextField(blank=True, default="")),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_decisions",
                        to="documents.nonpersonentity",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "candidate_id"),
                        name="uniq_reviewed_non_person_entity_decision_source_candidate",
                    )
                ],
            },
        ),
    ]
