# Generated by Django 6.0.1 on 2026-10-05 08:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0072_non_person_entity_foundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveItemEntityOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_kind",
                    models.CharField(
                        choices=[
                            ("MANUAL_TEXT", "MANUAL_TEXT"),
                            ("OCR_TRANSCRIPTION", "OCR_TRANSCRIPTION"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source_text_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator("^[0-9a-f]{64}$")
                        ],
                    ),
                ),
                (
                    "normalization_version",
                    models.CharField(default="surface-v1", max_length=32),
                ),
                ("normalized_surface", models.CharField(max_length=255)),
                (
                    "occurrence_ordinal",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("RESOLVED", "RESOLVED"),
                            ("UNRESOLVED", "UNRESOLVED"),
                        ],
                        max_length=16,
                    ),
                ),
                ("matched_text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archive_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_occurrences",
                        to="documents.archiveitem",
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archive_item_occurrences",
                        to="documents.reviewednonpersonentitydecision",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archive_item_occurrences",
                        to="documents.nonpersonentity",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "archive_item",
                            "text_kind",
                            "source_text_sha256",
                            "normalization_version",
                            "normalized_surface",
                            "occurrence_ordinal",
                        ),
                        name="uniq_archive_item_entity_occurrence_identity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("entity__isnull", False),
                                ("resolution_status", "RESOLVED"),
                            ),
                            models.Q(
                                ("entity__isnull", True),
                                ("resolution_status", "UNRESOLVED"),
                            ),
                            _connector="OR",
                        ),
                        name="archive_item_entity_occurrence_resolution_entity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("occurrence_ordinal__gte", 1)),
                        name="archive_item_entity_occurrence_ordinal_gte_1",
                    ),
                ],
            },
        ),
    ]
