# Generated by Django 6.0.1 on 2026-10-06 16:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0073_archive_item_entity_occurrence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NonPersonEntityOccurrenceProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_kind",
                    models.CharField(
                        choices=[
                            ("MANUAL_TEXT", "MANUAL_TEXT"),
                            ("OCR_TRANSCRIPTION", "OCR_TRANSCRIPTION"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source_text_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator("^[0-9a-f]{64}$")
                        ],
                    ),
                ),
                (
                    "normalization_version",
                    models.CharField(default="surface-v1", max_length=32),
                ),
                ("normalized_surface", models.CharField(max_length=255)),
                (
                    "occurrence_ordinal",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("matched_text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archive_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_occurrence_proposals",
                        to="documents.archiveitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NonPersonEntityOccurrenceCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("NEEDS_RESEARCH", "NEEDS_RESEARCH"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("REMOVED", "REMOVED"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occurrence_candidates",
                        to="documents.nonpersonentity",
                    ),
                ),
                (
                    "resolved_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occurrence_candidate_resolutions",
                        to="documents.nonpersonentity",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_non_person_occurrence_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="documents.nonpersonentityoccurrenceproposal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NonPersonEntityOccurrenceReviewEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("PROPOSE", "PROPOSE"),
                            ("DETECT", "DETECT"),
                            ("APPROVE", "APPROVE"),
                            ("REJECT", "REJECT"),
                            ("NEEDS_RESEARCH", "NEEDS_RESEARCH"),
                            ("REASSIGN", "REASSIGN"),
                            ("REMOVE", "REMOVE"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="non_person_occurrence_review_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="review_events",
                        to="documents.nonpersonentityoccurrencecandidate",
                    ),
                ),
                (
                    "from_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occurrence_review_events_from",
                        to="documents.nonpersonentity",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_events",
                        to="documents.nonpersonentityoccurrenceproposal",
                    ),
                ),
                (
                    "to_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occurrence_review_events_to",
                        to="documents.nonpersonentity",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="NonPersonEntityOccurrenceCandidateMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CANONICAL_NAME", "CANONICAL_NAME"),
                            ("DISPLAY_NAME", "DISPLAY_NAME"),
                            ("ALIAS", "ALIAS"),
                            ("MANUAL", "MANUAL"),
                        ],
                        max_length=32,
                    ),
                ),
                ("matched_value", models.CharField(max_length=255)),
                ("alias_kind", models.CharField(blank=True, default="", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="documents.nonpersonentityoccurrencecandidate",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("candidate", "method", "matched_value"),
                        name="uniq_non_person_occ_candidate_match",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="nonpersonentityoccurrenceproposal",
            constraint=models.UniqueConstraint(
                fields=(
                    "archive_item",
                    "text_kind",
                    "source_text_sha256",
                    "normalization_version",
                    "normalized_surface",
                    "occurrence_ordinal",
                ),
                name="uniq_non_person_occ_proposal_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="nonpersonentityoccurrenceproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(("occurrence_ordinal__gte", 1)),
                name="non_person_occ_proposal_ordinal_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="nonpersonentityoccurrencecandidate",
            constraint=models.UniqueConstraint(
                fields=("proposal", "candidate_entity"),
                name="uniq_non_person_occ_candidate_proposal_entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="nonpersonentityoccurrencecandidate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("resolved_entity__isnull", True), ("status", "PENDING")),
                    models.Q(
                        ("resolved_entity__isnull", True), ("status", "NEEDS_RESEARCH")
                    ),
                    models.Q(("resolved_entity__isnull", True), ("status", "REJECTED")),
                    models.Q(
                        ("resolved_entity__isnull", False), ("status", "APPROVED")
                    ),
                    ("status", "REMOVED"),
                    _connector="OR",
                ),
                name="non_person_occ_candidate_status_resolution",
            ),
        ),
    ]
