from django.urls import path

from . import views

urlpatterns = [
    path("", views.archive_list_page, name="archive-list"),
    path(
        "categories/<int:category_id>/",
        views.archive_category_browse_page,
        name="archive-category-browse",
    ),
    path(
        "events/<int:event_id>/",
        views.archive_event_browse_page,
        name="archive-event-browse",
    ),
    path(
        "tags/<int:tag_id>/",
        views.archive_tag_browse_page,
        name="archive-tag-browse",
    ),
    path(
        "people/<int:person_id>/",
        views.archive_person_detail_page,
        name="archive-person-detail",
    ),
    path("manage/", views.archive_manage_list_page, name="archive-manage-list"),
    path(
        "manage/new/",
        views.archive_manage_new_page,
        name="archive-manage-new",
    ),
    path(
        "manage/new/manual-text/",
        views.archive_manage_manual_text_create_page,
        name="archive-manage-manual-text-create",
    ),
    path(
        "manage/<int:item_id>/edit/",
        views.archive_manage_edit_page,
        name="archive-manage-edit",
    ),
    path(
        "manage/<int:item_id>/photos/add/",
        views.archive_manage_photo_add_page,
        name="archive-manage-photo-add",
    ),
    path(
        "manage/<int:item_id>/photos/reorder/",
        views.archive_manage_photo_reorder,
        name="archive-manage-photo-reorder",
    ),
    path(
        "manage/<int:item_id>/photos/<int:photo_id>/edit/",
        views.archive_manage_photo_edit_page,
        name="archive-manage-photo-edit",
    ),
    path(
        "manage/<int:item_id>/photos/<int:photo_id>/delete/",
        views.archive_manage_photo_delete_page,
        name="archive-manage-photo-delete",
    ),
    path(
        "manage/<int:item_id>/delete/",
        views.archive_manage_delete_page,
        name="archive-manage-delete",
    ),
    path(
        "manage/family-access/",
        views.archive_manage_family_access_page,
        name="archive-manage-family-access",
    ),
    path(
        "manage/people/<int:person_id>/edit/",
        views.archive_manage_person_edit_page,
        name="archive-manage-person-edit",
    ),
    path(
        "manage/people/<int:person_id>/aliases/<int:alias_id>/edit/",
        views.archive_manage_person_alias_edit_page,
        name="archive-manage-person-alias-edit",
    ),
    path(
        "manage/people/<int:person_id>/aliases/<int:alias_id>/delete/",
        views.archive_manage_person_alias_delete_page,
        name="archive-manage-person-alias-delete",
    ),
    path(
        "<int:item_id>/metadata-suggestions/new/",
        views.archive_metadata_suggestion_form,
        name="archive-metadata-suggestion-new",
    ),
    path(
        "<int:item_id>/metadata-suggestions/thanks/",
        views.archive_metadata_suggestion_thanks,
        name="archive-metadata-suggestion-thanks",
    ),
    path("<int:item_id>/", views.archive_detail_page, name="archive-detail"),
]
